### ISSUE TITLE
can't run template on windows 10

### ISSUE THREAD

**Issue by BlockWaving** [eliasdorneles/beeware-android-template#6]
Hi @eliasdorneles.  I am new to cookiecutter and briefcase and followed https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html .  I am on Windows 10, and encountered the same issue as reported before.  

(BeeEnv) D:\bee_proj>cookiecutter https://github.com/pybee/Python-Android-template
Traceback (most recent call last):
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3_5.3.1\envs\BeeEnv\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\cookiecutter\repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\site-packages\cookiecutter\vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "d:\anaconda3_5.3.1\envs\beeenv\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/pybee/Python-Android-template']' returned non-zero exit status 128.

how should i solve this ?

**Comment by jvmaia** [comment]
Apparently this is a problem with cookiecutter on windows, found this [https://stackoverflow.com/questions/50555982/trying-to-use-cookiecutter-django-getting-errors-and-does-not-create-anything](stackoverflow question);
I don't know if that is really going to solve your problem, but it's worth a try =)
